import Head from 'next/head';
import styles from '../styles/Index.module.css';
import Image from 'next/image';
import { avatar, comicavatar } from '../../public';
import { AiOutlineTwitter } from 'react-icons/ai';
import { IoMdMail } from 'react-icons/io';
import { BsWhatsapp } from 'react-icons/bs';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.data}>
				<div className={styles.imgcontainer}>
					<Image
						src={comicavatar}
						layout='responsive'
						className={styles.comicavatar}
					/>
					<Image src={avatar} layout='responsive' className={styles.avatar} />
				</div>
				<h2 className={styles.role}>Frontend Developer</h2>
				<h1 className={styles.title}>Alfonso Martín</h1>
				<div className={styles.social}>
					<div className={styles.socialgroup}>
						<AiOutlineTwitter />
						<a
							href='https://twitter.com/alfonsomgdev'
							target='_blank'
							rel='noreferrer'
							className={styles.sociallink}
						>
							twitter
						</a>
					</div>
					<div className={styles.socialgroup}>
						<IoMdMail />
						<a
							href="mailto:alfonsomg.dev@gmail.com?subject=Got a Job for you&body=Hello Alfonso! let's talk about my project!:"
							target='_blank'
							rel='noreferrer'
							className={styles.sociallink}
						>
							email
						</a>
					</div>
					<div className={styles.socialgroup}>
						<BsWhatsapp />
						<a
							href='https://api.whatsapp.com/send?phone=+34690300025&text=Hello Alfonso! Got a job to talk to you about!'
							target='_blank'
							rel='noreferrer'
							className={styles.sociallink}
						>
							whatsapp
						</a>
					</div>
				</div>
			</div>
		</>
	);
}
